# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests for integration purposes"
  lane :test_ci do
    prepare

    run_tests(
      app_name: "DBCO",
      device: "iPhone 11 Pro",
      project: "DBCO.xcodeproj",
      scheme: "DBCO",
      reinstall_app: true,
      app_identifier: "nl.rijksoverheid.dbco",
      skip_slack: true
    )
  end

  desc "Build and deploy via Firebase"
  lane :deploy do
    prepare

    version = get_version_number(xcodeproj: "DBCO.xcodeproj", target: "DBCO", configuration: "Release")
    build_number = determine_build_number()

    increment_build_number(build_number: build_number, xcodeproj: "DBCO.xcodeproj")

    build_ios_app(
      scheme: "DBCO",
      configuration: "Ad Hoc",
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          "nl.rijksoverheid.dbco" => "GGD DBCO Ad Hoc"
        }
      }
    )

    firebase_app_distribution(
      app: "11:14711935107:ios:58f70d62749507a0074bb6",
      groups: "Testers"
    )

    inform_slack(
      default_payloads: [:git_author],
      message: "Successfully distributed beta build #{version} (#{build_number}) :rocket:",
    )
  end

  desc "Build and deploy via Firebase from CI"
  lane :deploy_ci do
    setup_ci(provider: "travis", force: true)

    import_certificate(
      certificate_path: ENV["CERTIFICATE_PATH"],
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ""
    )

    install_provisioning_profile(path: "fastlane/profiles/GGD_DBCO_Ad_Hoc.mobileprovision")

    deploy
  end

  private_lane :prepare do
    xcversion(version: "12.0")
  end

  private_lane :determine_build_number do |options|
      ENV['GITHUB_RUN_NUMBER']
  end

  private_lane :inform_slack do |options|
    unless ENV['SLACK_URL'].nil?
      slack(options)
    end
  end

end